### PR TITLE
Add DES litmus test

### PR DESCRIPTION
**Pull request by ayllon**

### CODE REVIEW

**Comment by mkuemmel** [comment]
I tried to run that test both in EDEN-2.1  and on my laptop. Doesn't work with a multitude of problems:
E           FileNotFoundError: sourcextractor++ binary not found in /home/mkuemmel/Work/Projects:/opt:/SourceXtractorPlusPlus/SourceXtractorPlusPlus/build.x86_64-ub20-gcc93-o2g/bin/sourcextractor++

ERROR tests/des/test_des.py::test_detection[levmar_classic] - astropy.io.registry.IORegistryError: Format could not be identified.

Well, I am assuming it is okay...

**Comment by ayllon** [comment]
Using `E-Run`? TBH I have never tried that way.

**Comment by ayllon** [comment]
Try now @mkuemmel. It should be possible to run with `E-Run SourceXtractorPlusPlus [version] pytest`

**Comment by mkuemmel** [comment]
I tried some stuff yesterday, but could not get it running.

Now it is:
> mkuemmel@bruce-2:~/Work/Projects/SourceXtractor-litmus$ E-Run SourceXtractorPlusPlus 0.16 pytest
> ImportError while loading conftest '/home/mkuemmel/Work/Projects/SourceXtractor-litmus/tests/conftest.py'.
>   File "/home/mkuemmel/Work/Projects/SourceXtractor-litmus/tests/conftest.py", line 97
>     cmd_args.extend([f'--{k.replace("_", "-")}'])
>                                               ^
> SyntaxError: invalid syntax

But that one runs (for whatever reasons):
> E-Run SourceXtractorPlusPlus 0.16 py.test-3 -m "not slow"

Thanks for changing this! There is lots of interesting information in these tests and the pdf's!

**Pull request merged**
